### ISSUE TITLE
Logger Not Outputting to Terminal

### ISSUE THREAD

**Issue by koladev32** [koladev32/sendhooks-engine#23]
Our current logging system outputs logs directly to files and not to the terminal (stdout). While having logs saved to files is valuable for historical purposes, not seeing real-time logs in the terminal makes it challenging to debug live issues or monitor the application's performance during development and testing.

## Proposed Solution:
1. **Dual Logging**: Modify our logger to simultaneously log to both files and the terminal. This ensures that developers can monitor real-time events while retaining the ability to review past logs.

## Implementation Details:
- Use multi-writer functionality, which allows writing the same log to multiple outputs.

**Comment by KayZhang52** [comment]
Hi, i would like to work on this issue. Should i just go ahead?

**Comment by koladev32** [comment]
@KayZhang52 yes please you wan work on the issue
